### ISSUE TITLE
[BUG] Plugin disables in paperspigot 1.8

### ISSUE THREAD

**Issue by PabloGirol** [Syrent/SayanVanish#317]
Error log:
```
[21:23:50` ERROR]: Error occurred while enabling SayanVanish v1.1.0-a148634 (Is it up to date?)
java.lang.NoSuchMethodError: 'void org.yaml.snakeyaml.parser.ParserImpl.<init>(org.yaml.snakeyaml.scanner.Scanner)'
	at org.sayandev.libs.stickynote.lib.spongepowered.configurate.yaml.ConfigurateYaml.loadConfigurate(ConfigurateYaml.java:36) ~[?:?]
	at org.sayandev.libs.stickynote.lib.spongepowered.configurate.yaml.YamlConfigurationLoader.loadInternal(YamlConfigurationLoader.java:158) ~[?:?]
	at org.sayandev.libs.stickynote.lib.spongepowered.configurate.yaml.YamlConfigurationLoader.loadInternal(YamlConfigurationLoader.java:42) ~[?:?]
	at org.sayandev.libs.stickynote.lib.spongepowered.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:155) ~[?:?]
	at org.sayandev.libs.stickynote.lib.spongepowered.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:63) ~[?:?]
	at org.sayandev.libs.stickynote.lib.spongepowered.configurate.loader.ConfigurationLoader.load(ConfigurationLoader.java:56) ~[?:?]
	at org.sayandev.sayanvanish.api.database.DatabaseConfig$Companion.fromConfig(DatabaseConfig.kt:39) ~[?:?]
	at org.sayandev.sayanvanish.api.database.DatabaseConfigKt.<clinit>(DatabaseConfig.kt:10) ~[?:?]
	at org.sayandev.sayanvanish.api.SayanVanishAPI.<init>(SayanVanishAPI.kt:13) ~[?:?]
	at org.sayandev.sayanvanish.api.SayanVanishAPI.<init>(SayanVanishAPI.kt:11) ~[?:?]
	at org.sayandev.sayanvanish.api.SayanVanishAPI.<clinit>(SayanVanishAPI.kt:85) ~[?:?]
	at org.sayandev.sayanvanish.bukkit.SayanVanish.onEnable(SayanVanish.kt:23) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:840) [?:?]
[21:23:50 INFO]: [SayanVanish] Disabling SayanVanish v1.1.0-a148634
```

**Comment by Syrent** [comment]
try this build and delete the `features` folder:
https://hangar.papermc.io/Syrent/SayanVanish/versions/1.2.0-SNAPSHOT-build.141

**Comment by PabloGirol** [comment]
This build works fine except for this little issue that doesn't prevent it from working

```
[19:06:47] [Server thread/ERROR]: [SayanVanish] Plugin SayanVanish v1.2.0-SNAPSHOT-build.141-f347556 has failed to register events for class org.sayandev.sayanvanish.bukkit.feature.features.prevent.FeaturePreventPickup because org/bukkit/event/entity/EntityPickupItemEvent does not exist.
```

**Comment by Syrent** [comment]
use this build: https://hangar.papermc.io/Syrent/SayanVanish/versions/1.2.0-SNAPSHOT-build.143
