### ISSUE TITLE
[Bukkit] AsyncTabCompleteEvent listener

### ISSUE THREAD

**Issue by PanHaskins** [Syrent/SayanVanish#328]
Most plugins on the server when I try to tab complete, it throws this error.

`[17:42:34 ERROR]: Could not pass event AsyncTabCompleteEvent to SayanVanish v1.3.0-32eb3ea
java.lang.ClassCastException: class org.sayandev.sayanvanish.lib.stickynote.lib.incendo.cloud.paper.ModernPaperBrigadier cannot be cast to class org.sayandev.sayanvanish.lib.stickynote.lib.incendo.cloud.bukkit.BukkitPluginRegistrationHandler (org.sayandev.sayanvanish.lib.stickynote.lib.incendo.cloud.paper.ModernPaperBrigadier and org.sayandev.sayanvanish.lib.stickynote.lib.incendo.cloud.bukkit.BukkitPluginRegistrationHandler are in unnamed module of loader 'SayanVanish-1.3.0-32eb3ea-bukkit.jar' @257b9c1c)
        at SayanVanish-1.3.0-32eb3ea-bukkit.jar/org.sayandev.sayanvanish.lib.stickynote.lib.incendo.cloud.paper.suggestion.AsyncCommandSuggestionListener.onTabCompletion(AsyncCommandSuggestionListener.java:57) ~[SayanVanish-1.3.0-32eb3ea-bukkit.jar:?]
        at SayanVanish-1.3.0-32eb3ea-bukkit.jar/org.sayandev.sayanvanish.lib.stickynote.lib.incendo.cloud.paper.suggestion.BrigadierAsyncCommandSuggestionListener.onTabCompletion(BrigadierAsyncCommandSuggestionListener.java:53) ~[SayanVanish-1.3.0-32eb3ea-bukkit.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2251-ac6c312]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2251-ac6c312]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2251-ac6c312]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.event.Event.callEvent(Event.java:45) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCustomCommandSuggestions0(ServerGamePacketListenerImpl.java:811) ~[purpur-1.21.jar:1.21-2251-ac6c312]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleCustomCommandSuggestions$1(ServerGamePacketListenerImpl.java:800) ~[purpur-1.21.jar:1.21-2251-ac6c312]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**Comment by Syrent** [comment]
hey, use last snapshot build from hangar or modrinth
