### ISSUE TITLE
[Bug] 1.5.0 latest on Velocity

### ISSUE THREAD

**Issue by mani1232** [Syrent/SayanVanish#334]
```
[15:31:43 ERROR]: Can't create plugin sayanvanish
com.google.inject.ProvisionException: Unable to provision, see the following errors:
1) [Guice/ErrorInjectingConstructor]: NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
  at SayanVanish.<init>(SayanVanish.kt:20)
  at VelocityPluginModule.configure(VelocityPluginModule.java:47)
  while locating SayanVanish
Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR
1 error
======================
Full classname legend:
======================
SayanVanish:          "org.sayandev.sayanvanish.velocity.SayanVanish"
VelocityPluginModule: "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
========================
End of classname legend:
========================
        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[velocity-proxy-3.3.0-SNAPSHOT-all.jar:3.3.0-SNAPSHOT (git-1af03daf)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1151) ~[velocity-proxy-3.3.0-SNAPSHOT-all.jar:3.3.0-SNAPSHOT (git-1af03daf)]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186) ~[velocity-proxy-3.3.0-SNAPSHOT-all.jar:3.3.0-SNAPSHOT (git-1af03daf)]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:131) ~[velocity-proxy-3.3.0-SNAPSHOT-all.jar:3.3.0-SNAPSHOT (git-1af03daf)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:168) ~[velocity-proxy-3.3.0-SNAPSHOT-all.jar:3.3.0-SNAPSHOT (git-1af03daf)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:420) ~[velocity-proxy-3.3.0-SNAPSHOT-all.jar:3.3.0-SNAPSHOT (git-1af03daf)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:260) ~[velocity-proxy-3.3.0-SNAPSHOT-all.jar:3.3.0-SNAPSHOT (git-1af03daf)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:71) ~[velocity-proxy-3.3.0-SNAPSHOT-all.jar:3.3.0-SNAPSHOT (git-1af03daf)]
Caused by: java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
        at org.sayandev.sayanvanish.velocity.SayanVanish.<init>(SayanVanish.kt) ~[?:?]
        at org.sayandev.sayanvanish.velocity.SayanVanish$$FastClassByGuice$$1ca256d.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at org.sayandev.sayanvanish.velocity.SayanVanish$$FastClassByGuice$$1ca256d.apply(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[velocity-proxy-3.3.0-SNAPSHOT-all.jar:3.3.0-SNAPSHOT (git-1af03daf)]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[velocity-proxy-3.3.0-SNAPSHOT-all.jar:3.3.0-SNAPSHOT (git-1af03daf)]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[velocity-proxy-3.3.0-SNAPSHOT-all.jar:3.3.0-SNAPSHOT (git-1af03daf)]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[velocity-proxy-3.3.0-SNAPSHOT-all.jar:3.3.0-SNAPSHOT (git-1af03daf)]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[velocity-proxy-3.3.0-SNAPSHOT-all.jar:3.3.0-SNAPSHOT (git-1af03daf)]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[velocity-proxy-3.3.0-SNAPSHOT-all.jar:3.3.0-SNAPSHOT (git-1af03daf)]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[velocity-proxy-3.3.0-SNAPSHOT-all.jar:3.3.0-SNAPSHOT (git-1af03daf)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[velocity-proxy-3.3.0-SNAPSHOT-all.jar:3.3.0-SNAPSHOT (git-1af03daf)]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[velocity-proxy-3.3.0-SNAPSHOT-all.jar:3.3.0-SNAPSHOT (git-1af03daf)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity-proxy-3.3.0-SNAPSHOT-all.jar:3.3.0-SNAPSHOT (git-1af03daf)]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at org.sayandev.sayanvanish.velocity.SayanVanish.<init>(SayanVanish.kt) ~[?:?]
        at org.sayandev.sayanvanish.velocity.SayanVanish$$FastClassByGuice$$1ca256d.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at org.sayandev.sayanvanish.velocity.SayanVanish$$FastClassByGuice$$1ca256d.apply(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[velocity-proxy-3.3.0-SNAPSHOT-all.jar:3.3.0-SNAPSHOT (git-1af03daf)]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[velocity-proxy-3.3.0-SNAPSHOT-all.jar:3.3.0-SNAPSHOT (git-1af03daf)]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[velocity-proxy-3.3.0-SNAPSHOT-all.jar:3.3.0-SNAPSHOT (git-1af03daf)]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[velocity-proxy-3.3.0-SNAPSHOT-all.jar:3.3.0-SNAPSHOT (git-1af03daf)]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[velocity-proxy-3.3.0-SNAPSHOT-all.jar:3.3.0-SNAPSHOT (git-1af03daf)]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[velocity-proxy-3.3.0-SNAPSHOT-all.jar:3.3.0-SNAPSHOT (git-1af03daf)]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[velocity-proxy-3.3.0-SNAPSHOT-all.jar:3.3.0-SNAPSHOT (git-1af03daf)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[velocity-proxy-3.3.0-SNAPSHOT-all.jar:3.3.0-SNAPSHOT (git-1af03daf)]
        ... 6 more
        ```

**Comment by Syrent** [comment]
fixed on this build:
https://hangar.papermc.io/Syrent/SayanVanish/versions/1.5.0-SNAPSHOT-build.183
