### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by Hiradpi** [Syrent/SayanVanish#338]
```
[20:14:33 INFO]: [SayanVanish] Found 35 features.
[20:14:33 ERROR]: Error occurred while enabling SayanVanish v1.4.0-build.17-ee9d82c (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/event/raid/RaidTriggerEvent
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?]
        at java.lang.Class.getDeclaredMethods(Class.java:2504) ~[?:?]
        at org.sayandev.sayanvanish.lib.stickynote.lib.spongepowered.configurate.util.Types.allDeclaredMethods(Types.java:561) ~[?:?]
        at org.sayandev.sayanvanish.lib.stickynote.lib.spongepowered.configurate.objectmapping.meta.PostProcessor.lambda$methodsAnnotated$1(PostProcessor.java:84) ~[?:?]
        at org.sayandev.sayanvanish.lib.stickynote.lib.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.computePostProcessors(ObjectMapperFactoryImpl.java:161) ~[?:?]
        at org.sayandev.sayanvanish.lib.stickynote.lib.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.newMapper(ObjectMapperFactoryImpl.java:146) ~[?:?]
        at org.sayandev.sayanvanish.lib.stickynote.lib.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.computeMapper(ObjectMapperFactoryImpl.java:128) ~[?:?]
        at org.sayandev.sayanvanish.lib.stickynote.lib.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.lambda$computeFromMap$5(ObjectMapperFactoryImpl.java:316) ~[?:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
        at org.sayandev.sayanvanish.lib.stickynote.lib.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.computeFromMap(ObjectMapperFactoryImpl.java:314) ~[?:?]
        at org.sayandev.sayanvanish.lib.stickynote.lib.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.get(ObjectMapperFactoryImpl.java:117) ~[?:?]
        at org.sayandev.sayanvanish.lib.stickynote.lib.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.emptyValue(ObjectMapperFactoryImpl.java:284) ~[?:?]
        at org.sayandev.sayanvanish.lib.stickynote.lib.spongepowered.configurate.AbstractConfigurationNode.get0(AbstractConfigurationNode.java:185) ~[?:?]
        at org.sayandev.sayanvanish.lib.stickynote.lib.spongepowered.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:161) ~[?:?]
        at org.sayandev.sayanvanish.lib.stickynote.lib.spongepowered.configurate.ConfigurationNode.get(ConfigurationNode.java:521) ~[?:?]
        at org.sayandev.sayanvanish.api.feature.Feature$Companion.createFromConfig(Feature.kt:58) ~[?:?]
        at org.sayandev.sayanvanish.api.feature.RegisteredFeatureHandler.createNewInstance(RegisteredFeatureHandler.kt:35) ~[?:?]
        at org.sayandev.sayanvanish.api.feature.RegisteredFeatureHandler.process(RegisteredFeatureHandler.kt:27) ~[?:?]
        at org.sayandev.sayanvanish.api.Platform$Companion.register(Platform.kt:25) ~[?:?]
        at org.sayandev.sayanvanish.api.Platform$Companion.setAndRegister(Platform.kt:31) ~[?:?]
        at org.sayandev.sayanvanish.bukkit.SayanVanish.onEnable(SayanVanish.kt:21) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.event.raid.RaidTriggerEvent
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 33 more
[20:14:33 INFO]: [SayanVanish] Disabling SayanVanish v1.4.0-build.17-ee9d82c

```
paper 1.8

**Comment by Syrent** [comment]
hey, your sayanvanish build is 175 versions behind please switch to latest snapshot version:
https://hangar.papermc.io/Syrent/SayanVanish/versions/1.5.0-SNAPSHOT-build.192

**Comment by Hiradpi** [comment]
well there is an another issue i did update but after that when i want to vanish 
![image](https://github.com/user-attachments/assets/56819b37-6254-49f0-abb2-5c25123222cf)
( i have * permissions ) 
(proxy option is enabled) 
and mysql is connected

**Comment by Syrent** [comment]
check this part on SayanVanish wiki:
https://docs.sayandev.org/sayanvanish/faq#sayanvanish-doesnt-recognize-permission-or-operator-status

**Comment by Hiradpi** [comment]
> check this part on SayanVanish wiki: https://docs.sayandev.org/sayanvanish/faq#sayanvanish-doesnt-recognize-permission-or-operator-status

thanks 
and one more thing 
what messaging plugin do you recommend to use ? for now players can bypass vanish by doing /msg vanished_player 
im on latest waterfall and paper 1.8.9

**Comment by Syrent** [comment]
any plugin that supports "Vanished" meta will support SayanVanish too. what plugin are you using for chat?
