### ISSUE TITLE
Task generated an exception

### ISSUE THREAD

**Issue by Deb4ikOff** [Syrent/SayanVanish#339]
When i turned on vanish, that happend

```
[SayanVanish] Task #149308 for SayanVanish v1.4.0-ee9d82c generated an exception
java.lang.NullPointerException: null
at SayanVanish-1.4.0-ee9d82c-bukkit.jar/org.sayandev.sayanvanish.lib.stickynote.bukkit.nms.PacketUtils.getRemoveEntitiesPacket(PacketUtils.kt:208) ~[SayanVanish-1.4.0-ee9d82c-bukkit.jar:?]
at SayanVanish-1.4.0-ee9d82c-bukkit.jar/org.sayandev.sayanvanish.bukkit.feature.features.FeatureLevel.onVanish$lambda$3(FeatureLevel.kt:40) ~[SayanVanish-1.4.0-ee9d82c-bukkit.jar:?]
at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1763) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1635) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1335) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2295-c4a6f63]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

After this players still can see me in general, and player counter from essentials count me too.

![image](https://github.com/user-attachments/assets/6fa0e107-ca8b-4265-8f14-79f8f7f78776)

upd1: This happens even when a player joins

**Comment by Syrent** [comment]
use latest snapshot build:
https://hangar.papermc.io/Syrent/SayanVanish/versions/1.5.0-SNAPSHOT-build.192

**Comment by Deb4ikOff** [comment]
ok, that was solved a problem. but new apper, i can't teleport via spectator hotbar... i turned off all preventions, toggled off vanish, but still can't tp...

**Comment by Deb4ikOff** [comment]
> use latest snapshot build: https://hangar.papermc.io/Syrent/SayanVanish/versions/1.5.0-SNAPSHOT-build.192

ok, that was solved a problem. but new apper, i can't teleport via spectator hotbar... i turned off all preventions, toggled off vanish, but still can't tp...

**Comment by Syrent** [comment]
try this build:
https://hangar.papermc.io/Syrent/SayanVanish/versions/1.5.0-SNAPSHOT-build.195

**Comment by Deb4ikOff** [comment]
> try this build: https://hangar.papermc.io/Syrent/SayanVanish/versions/1.5.0-SNAPSHOT-build.195
yea, it helped
