### ISSUE TITLE
[Bug] Error loading plugin in latest velocity

### ISSUE THREAD

**Issue by Aruvelut-123** [Syrent/SayanVanish#343]
`[13:07:44 ERROR]: Couldn't pass ProxyInitializeEvent to sayanvanish 1.5.0-SNAPSHOT-build.195-7864f46
java.lang.NoClassDefFoundError: org/sayandev/sayanvanish/lib/stickynote/core/configuration/Config
        at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?]
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?]
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:714) ~[?:?]
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:70) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b
436)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b4
36)]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at org.sayandev.sayanvanish.proxy.config.SettingsConfigKt.<clinit>(SettingsConfig.kt:9) ~[?:?]
        at org.sayandev.sayanvanish.velocity.SayanVanish.onProxyInitialize(SayanVanish.kt:33) ~[?:?]
        at org.sayandev.sayanvanish.velocity.Lmbda$33.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-436.ja
r:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:676) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b
436)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:541) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2
016d148-b436)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassNotFoundException: org.sayandev.sayanvanish.lib.stickynote.core.configuration.Config
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b
436)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b4
36)]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]`
`[13:08:54 INFO]: Velocity 3.3.0-SNAPSHOT (git-2016d148-b436)
[13:08:54 INFO]: Copyright 2018-2023 Velocity Contributors。Velocity 以 GNU 通用公共许可证第三版授权。
[13:08:54 INFO]: velocitypowered.com - GitHub`

**Comment by Syrent** [comment]
Send full server log

**Comment by Aruvelut-123** [comment]
https://pastebin.com/B1wksjB7

**Comment by Syrent** [comment]
sayanvanish requires internet connection to work, you server can't connect to any of the required repositories to download its dependencies

**Comment by Aruvelut-123** [comment]
is it possible to move the repository  to somewhere that china can visit

**Comment by Syrent** [comment]
unfortunately, no, there are quite a few repositories involved. one approach that might work is to set up SayanVanish on a server with a reliable internet connection, then copy the `plugin/SayanVanish/libs` directory from there and transfer it to your server
