### ISSUE TITLE
Support 1.21.2/3

### ISSUE THREAD

**Issue by mani1232** [Syrent/SayanVanish#349]
```
[16:58:27 ERROR]: Could not pass event PlayerGameModeChangeEvent to SayanVanish v1.5.1-SNAPSHOT-build.202-cd60777
java.lang.NullPointerException: null
        at SayanVanish-1.5.1-SNAPSHOT-build.202-cd60777-bukkit.jar/org.sayandev.sayanvanish.lib.stickynote.bukkit.nms.PacketUtils.getRemoveEntitiesPacket(PacketUtils.kt:197) ~[SayanVanish-1.5.1-SNAPSHOT-build.202-cd60777-bukkit.jar:?]
        at SayanVanish-1.5.1-SNAPSHOT-build.202-cd60777-bukkit.jar/org.sayandev.sayanvanish.bukkit.feature.features.FeatureLevel.onGameModeChange(FeatureLevel.kt:77) ~[SayanVanish-1.5.1-SNAPSHOT-build.202-cd60777-bukkit.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:44) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.changeGameModeForPlayer(ServerPlayerGameMode.java:89) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.server.level.ServerPlayer.setGameMode(ServerPlayer.java:2438) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at org.bukkit.craftbukkit.entity.CraftPlayer.setGameMode(CraftPlayer.java:1866) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at SayanVanish-1.5.1-SNAPSHOT-build.202-cd60777-bukkit.jar/org.sayandev.sayanvanish.bukkit.feature.features.FeatureSilentContainer.onInventoryClose(FeatureSilentContainer.kt:90) ~[SayanVanish-1.5.1-SNAPSHOT-build.202-cd60777-bukkit.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:44) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1644) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:2983) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:2976) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.handle(ServerboundContainerClosePacket.java:33) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.handle(ServerboundContainerClosePacket.java:15) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1576) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1553) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1546) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:138) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1497) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1507) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1343) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:339) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[16:58:28 ERROR]: Could not pass event PlayerGameModeChangeEvent to SayanVanish v1.5.1-SNAPSHOT-build.202-cd60777
java.lang.NullPointerException: null
        at SayanVanish-1.5.1-SNAPSHOT-build.202-cd60777-bukkit.jar/org.sayandev.sayanvanish.lib.stickynote.bukkit.nms.PacketUtils.getRemoveEntitiesPacket(PacketUtils.kt:197) ~[SayanVanish-1.5.1-SNAPSHOT-build.202-cd60777-bukkit.jar:?]
        at SayanVanish-1.5.1-SNAPSHOT-build.202-cd60777-bukkit.jar/org.sayandev.sayanvanish.bukkit.feature.features.FeatureLevel.onGameModeChange(FeatureLevel.kt:77) ~[SayanVanish-1.5.1-SNAPSHOT-build.202-cd60777-bukkit.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:44) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.changeGameModeForPlayer(ServerPlayerGameMode.java:89) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.server.level.ServerPlayer.setGameMode(ServerPlayer.java:2438) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at org.bukkit.craftbukkit.entity.CraftPlayer.setGameMode(CraftPlayer.java:1866) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at SayanVanish-1.5.1-SNAPSHOT-build.202-cd60777-bukkit.jar/org.sayandev.sayanvanish.bukkit.feature.features.FeatureSilentContainer$ContainerPlayerData.apply(FeatureSilentContainer.kt:104) ~[SayanVanish-1.5.1-SNAPSHOT-build.202-cd60777-bukkit.jar:?]
        at SayanVanish-1.5.1-SNAPSHOT-build.202-cd60777-bukkit.jar/org.sayandev.sayanvanish.bukkit.feature.features.FeatureSilentContainer.onInventoryClose$lambda$1(FeatureSilentContainer.kt:93) ~[SayanVanish-1.5.1-SNAPSHOT-build.202-cd60777-bukkit.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:474) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1801) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1662) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1328) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:339) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Syrent** [comment]
try version 1.5.2

**Comment by Syrent** [comment]
i'll close this issue, re-open it if its not resolved.
