### ISSUE TITLE
Issue with SayanVanish v1.6.1 PaperSpigot 1.8

### ISSUE THREAD

**Issue by PabloGirol** [Syrent/SayanVanish#357]
The issue is that SayanVanish seems to be trying to register a channel too long for this version at least

```

[22:07:01] [Server thread/ERROR]: [SayanVanish] Plugin SayanVanish v1.6.1-362232a has failed to register events for class org.sayandev.sayanvanish.bukkit.feature.features.prevent.FeaturePreventTabComplete because org/bukkit/event/server/TabCompleteEvent does not exist.

[22:07:02] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: sayanvanish [1.6.1-362232a]
[22:07:02] [Server thread/INFO]: [SayanVanish] Enabled 20 features.
[22:07:03] [Server thread/ERROR]: Error occurred while enabling SayanVanish v1.6.1-362232a (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at org.sayandev.sayanvanish.bukkit.SayanVanish.onEnable(SayanVanish.kt:37) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: org.bukkit.plugin.messaging.ChannelNameTooLongException: Attempted to send a Plugin Message to a channel that was too large. The maximum length a channel may be is 20 chars (attempted 23 - 'sayanvanish:healthcheck.
	at org.bukkit.plugin.messaging.StandardMessenger.validateChannel(StandardMessenger.java:454) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.messaging.StandardMessenger.registerOutgoingPluginChannel(StandardMessenger.java:180) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.sayandev.sayanvanish.lib.stickynote.bukkit.messaging.publisher.PluginMessagePublisher.registerChannel(PluginMessagePublisher.kt:32) ~[?:?]
	at org.sayandev.sayanvanish.lib.stickynote.bukkit.messaging.publisher.PluginMessagePublisher.<init>(PluginMessagePublisher.kt:28) ~[?:?]
	at org.sayandev.sayanvanish.lib.stickynote.bukkit.messaging.publisher.ProxyPluginMessagePublisher.<init>(ProxyPluginMessagePublisher.kt:8) ~[?:?]
	at org.sayandev.sayanvanish.bukkit.health.HealthCheckRequestPublisher.<init>(HealthCheckRequestPublisher.kt:7) ~[?:?]
	at org.sayandev.sayanvanish.bukkit.health.HealthCheckRequestPublisher.<clinit>(HealthCheckRequestPublisher.kt) ~[?:?]
	... 12 more
[22:07:03] [Server thread/INFO]: [SayanVanish] Disabling SayanVanish v1.6.1-362232a
```

**Comment by Syrent** [comment]
try this build:
https://hangar.papermc.io/Syrent/SayanVanish/versions/1.6.2-SNAPSHOT-build.220

**Comment by PabloGirol** [comment]
Seems to work fine as of now
